try {
    console.log(a);
} catch (err) {
    console.log(err);
} finally {
    console.log("finished");
}
